-- VHDL Entity ece411.Cache_Datapath.interface
--
-- Created:
--          by - strasbe1.ews (gelib-057-05.ews.illinois.edu)
--          at - 19:59:44 02/17/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee; 
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all; 
 
LIBRARY ece411; 
USE ece411.LC3b_types.all; 

ENTITY Cache_Datapath IS
   PORT( 
      ADDRESS   : IN     LC3b_word;
      CLK       : IN     STD_LOGIC;
      DATAOUT   : IN     LC3b_word;
      MREAD_L   : IN     std_logic;
      MWRITEH_L : IN     std_logic;
      MWRITEL_L : IN     std_logic;
      PMDATAIN  : IN     LC3B_OWORD;
      Reset_L   : IN     std_logic;
      DATAIN    : OUT    LC3b_word;
      Hit       : OUT    std_logic;
      MRESP_H   : OUT    std_logic;
      PMADDRESS : OUT    LC3B_WORD;
      PMDATAOUT : OUT    LC3B_OWORD
   );

-- Declarations

END Cache_Datapath ;

--
-- VHDL Architecture ece411.Cache_Datapath.struct
--
-- Created:
--          by - strasbe1.ews (gelib-057-05.ews.illinois.edu)
--          at - 19:59:44 02/17/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee; 
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all; 
 
LIBRARY ece411; 
USE ece411.LC3b_types.all; 


ARCHITECTURE struct OF Cache_Datapath IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL CacheWay1DataOut : LC3B_OWORD;
   SIGNAL Index            : LC3b_c_index;
   SIGNAL Tag              : LC3b_c_tag;
   SIGNAL TagOut           : LC3b_c_tag;
   SIGNAL ValidOut         : std_logic;
   SIGNAL Way1Andout       : std_logic;
   SIGNAL WriteOrOut       : std_logic;
   SIGNAL dataOutsel       : LC3B_8MUX_SEL;
   SIGNAL offset           : LC3b_c_offset;
   SIGNAL way1equal        : std_logic;
   SIGNAL word0            : LC3B_WORD;
   SIGNAL word1            : LC3B_WORD;
   SIGNAL word2            : LC3B_WORD;
   SIGNAL word3            : LC3B_WORD;
   SIGNAL word4            : LC3B_WORD;
   SIGNAL word5            : LC3B_WORD;
   SIGNAL word6            : LC3B_WORD;
   SIGNAL word7            : LC3B_WORD;

   -- Implicit buffer signal declarations
   SIGNAL PMDATAOUT_internal : LC3B_OWORD;


   -- Component Declarations
   COMPONENT AND2
   PORT (
      A : IN     std_logic;
      B : IN     std_logic;
      C : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT AddressParts
   PORT (
      ADDRESS : IN     LC3b_word ;
      Tag     : OUT    LC3b_c_tag ;
      Index   : OUT    LC3b_c_index ;
      offset  : OUT    LC3b_c_offset 
   );
   END COMPONENT;
   COMPONENT CacheWay
   PORT (
      DataIn    : IN     LC3b_oword ;
      DataWrite : IN     std_logic ;
      Index     : IN     LC3B_C_INDEX ;
      Reset_L   : IN     std_logic ;
      TagIn     : IN     LC3B_C_TAG ;
      DataOut   : OUT    LC3B_OWORD ;
      DirtyOut  : OUT    std_logic ;
      TagOut    : OUT    LC3b_c_tag ;
      ValidOut  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT DataOutBreakup
   PORT (
      PMDATAOUT : IN     LC3B_OWORD ;
      word0     : OUT    LC3B_WORD ;
      word1     : OUT    LC3B_WORD ;
      word2     : OUT    LC3B_WORD ;
      word3     : OUT    LC3B_WORD ;
      word4     : OUT    LC3B_WORD ;
      word5     : OUT    LC3B_WORD ;
      word6     : OUT    LC3B_WORD ;
      word7     : OUT    LC3B_WORD 
   );
   END COMPONENT;
   COMPONENT Mux8
   PORT (
      dataOutsel : IN     LC3B_8MUX_SEL ;
      word0      : IN     LC3B_WORD ;
      word1      : IN     LC3B_WORD ;
      word2      : IN     LC3B_WORD ;
      word3      : IN     LC3B_WORD ;
      word4      : IN     LC3B_WORD ;
      word5      : IN     LC3B_WORD ;
      word6      : IN     LC3B_WORD ;
      word7      : IN     LC3B_WORD ;
      DATAIN     : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     std_logic;
      B : IN     std_logic;
      C : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT OWordMux
   PORT (
      A   : IN     LC3b_oword;
      B   : IN     LC3b_oword;
      Sel : IN     std_logic;
      F   : OUT    LC3b_oword
   );
   END COMPONENT;
   COMPONENT OffsetWord
   PORT (
      offset     : IN     LC3b_c_offset ;
      dataOutsel : OUT    LC3B_8MUX_SEL 
   );
   END COMPONENT;
   COMPONENT PMAddrOffset
   PORT (
      ADDRESS   : IN     LC3b_word ;
      PMADDRESS : OUT    LC3B_WORD 
   );
   END COMPONENT;
   COMPONENT TagComparator
   PORT (
      A     : IN     LC3b_c_tag;
      B     : IN     LC3b_c_tag;
      equal : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY ece411.AND2;
   FOR ALL : AddressParts USE ENTITY ece411.AddressParts;
   FOR ALL : CacheWay USE ENTITY ece411.CacheWay;
   FOR ALL : DataOutBreakup USE ENTITY ece411.DataOutBreakup;
   FOR ALL : Mux8 USE ENTITY ece411.Mux8;
   FOR ALL : OR2 USE ENTITY ece411.OR2;
   FOR ALL : OWordMux USE ENTITY ece411.OWordMux;
   FOR ALL : OffsetWord USE ENTITY ece411.OffsetWord;
   FOR ALL : PMAddrOffset USE ENTITY ece411.PMAddrOffset;
   FOR ALL : TagComparator USE ENTITY ece411.TagComparator;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   Way1And : AND2
      PORT MAP (
         A => way1equal,
         B => ValidOut,
         C => Way1Andout
      );
   aAddressParts : AddressParts
      PORT MAP (
         ADDRESS => ADDRESS,
         Tag     => Tag,
         Index   => Index,
         offset  => offset
      );
   CacheWay1 : CacheWay
      PORT MAP (
         DataIn    => PMDATAIN,
         DataWrite => WriteOrOut,
         Index     => Index,
         Reset_L   => Reset_L,
         TagIn     => Tag,
         DataOut   => CacheWay1DataOut,
         DirtyOut  => OPEN,
         TagOut    => TagOut,
         ValidOut  => ValidOut
      );
   aDataOutBreakup : DataOutBreakup
      PORT MAP (
         PMDATAOUT => PMDATAOUT_internal,
         word0     => word0,
         word1     => word1,
         word2     => word2,
         word3     => word3,
         word4     => word4,
         word5     => word5,
         word6     => word6,
         word7     => word7
      );
   DataInMux : Mux8
      PORT MAP (
         dataOutsel => dataOutsel,
         word0      => word0,
         word1      => word1,
         word2      => word2,
         word3      => word3,
         word4      => word4,
         word5      => word5,
         word6      => word6,
         word7      => word7,
         DATAIN     => DATAIN
      );
   HitOR : OR2
      PORT MAP (
         A => Way1Andout,
         B => Way1Andout,
         C => Hit
      );
   WriteOr : OR2
      PORT MAP (
         A => MWRITEH_L,
         B => MWRITEL_L,
         C => WriteOrOut
      );
   U_1 : OWordMux
      PORT MAP (
         A   => CacheWay1DataOut,
         B   => CacheWay1DataOut,
         Sel => Way1Andout,
         F   => PMDATAOUT_internal
      );
   aOffsetWord : OffsetWord
      PORT MAP (
         offset     => offset,
         dataOutsel => dataOutsel
      );
   aPmAddrOffset : PMAddrOffset
      PORT MAP (
         ADDRESS   => ADDRESS,
         PMADDRESS => PMADDRESS
      );
   Way1Comparator : TagComparator
      PORT MAP (
         A     => Tag,
         B     => TagOut,
         equal => way1equal
      );

   -- Implicit buffered output assignments
   PMDATAOUT <= PMDATAOUT_internal;

END struct;
