-- VHDL Entity ece411.Cache_Controller.interface
--
-- Created:
--          by - strasbe1.ews (gelib-057-28.ews.illinois.edu)
--          at - 23:02:55 03/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee; 
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all; 
 
LIBRARY ece411; 
USE ece411.LC3b_types.all; 

ENTITY Cache_Controller IS
   PORT( 
      CLK          : IN     STD_LOGIC;
      DirtyCache   : IN     std_logic;
      Hit          : IN     std_logic;
      MemRead      : IN     std_logic;
      MemWrite     : IN     std_logic;
      PMRESP_H     : IN     STD_LOGIC;
      RESET_L      : IN     std_logic;
      CacheWrite   : OUT    std_logic;
      DAtaWriteSel : OUT    std_logic;
      DirtyIn      : OUT    std_logic;
      DirtyState   : OUT    std_logic;
      DirtyWrite   : OUT    std_logic;
      LRUHold      : OUT    std_logic;
      PMREAD_L     : OUT    STD_LOGIC;
      PMWRITE_L    : OUT    STD_LOGIC;
      PauseHits_L  : OUT    std_logic
   );

-- Declarations

END Cache_Controller ;

--
-- VHDL Architecture ece411.Cache_Controller.fsm
--
-- Created:
--          by - strasbe1.ews (gelib-057-28.ews.illinois.edu)
--          at - 23:02:55 03/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee; 
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all; 
 
LIBRARY ece411; 
USE ece411.LC3b_types.all; 
 
ARCHITECTURE fsm OF Cache_Controller IS

   TYPE STATE_TYPE IS (
      Check,
      Miss,
      SETLRU,
      Write,
      Dirty
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      CLK,
      Reset_L
   )
   -----------------------------------------------------------------
   BEGIN
      IF (Reset_L = '0') THEN
         current_state <= Check;
      ELSIF (CLK'EVENT AND CLK = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      DirtyCache,
      Hit,
      MemWrite,
      PMRESP_H,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN Check => 
            IF ((hit = '0') AND
                (DirtyCache = '1')) THEN 
               next_state <= Dirty;
            ELSIF ((Hit = '0') AND
                   (DirtyCache = '0')) THEN 
               next_state <= Miss;
            ELSIF ((memWrite = '1') AND
                   (Hit = '1')) THEN 
               next_state <= Write;
            ELSE
               next_state <= Check;
            END IF;
         WHEN Miss => 
            IF ((PMRESP_H = '1') AND
                (memWrite ='0')) THEN 
               next_state <= SETLRU;
            ELSIF ((memWrite = '1') AND
                   (PMRESP_H = '1')) THEN 
               next_state <= Write;
            ELSE
               next_state <= Miss;
            END IF;
         WHEN SETLRU => 
            next_state <= Check;
         WHEN Write => 
            next_state <= SETLRU;
         WHEN Dirty => 
            IF (PMRESP_H = '1') THEN 
               next_state <= Check;
            ELSE
               next_state <= Dirty;
            END IF;
         WHEN OTHERS =>
            next_state <= Check;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      CacheWrite <= '0';
      DAtaWriteSel <= '0';
      DirtyIn <= '0';
      DirtyState <= '0';
      DirtyWrite <= '0';
      LRUHold <= '0';
      PMREAD_L <= '1';
      PMWRITE_L <= '1';
      PauseHits_L <= '1';

      -- Combined Actions
      CASE current_state IS
         WHEN Miss => 
            PMREAD_L <= '0' after 6ns;
            PauseHits_L <= '0';
            cacheWrite <= '1';
         WHEN SETLRU => 
            LRUHOLD <= '1';
            PauseHits_L <= '0';
         WHEN Write => 
            PauseHits_L <= '0';
            DataWriteSel <= '1';
            CacheWrite <= '1';
            DirtyWrite <= '1';
            DirtyIn <= '1';
         WHEN Dirty => 
            PMWRITE_L <= '0' after 6ns;
            DirtyWrite <= '1';
            DirtyIn <= '0';
            PauseHits_L <= '0';
            DirtyState <= '1';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
