-- VHDL Entity ece411.DataOutWrite.generatedInstance
--
-- Created:
--          by - strasbe1.ews (dcl-l520-32.ews.illinois.edu)
--          at - 17:50:33 03/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee; 
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all; 
 
LIBRARY ece411; 
USE ece411.LC3b_types.all; 

ENTITY DataOutWrite IS
   PORT( 
      DATAOUT      : IN     LC3b_word;
      DataWriteOut : OUT    LC3B_Oword;
      MWRITEH_L    : IN     std_logic;
      MWRITEL_L    : IN     std_logic;
      offset       : IN     LC3b_c_offset;
      PMDATAOUT    : IN     LC3B_OWORD
   );

END DataOutWrite ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF DataOutWrite IS 
BEGIN


END generatedInstance;
