-- VHDL Entity ece411.Imm5.generatedInstance
--
-- Created:
--          by - strasbe1.ews (dcl-l520-33.ews.illinois.edu)
--          at - 21:50:33 02/06/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Imm5 IS
   PORT( 
      clk        : IN     std_logic;
      Imm5out    : OUT    LC3b_word;
      immediate5 : IN     LC3b_imm5
   );

END Imm5 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Imm5 IS 
BEGIN


END generatedInstance;
