-- VHDL Entity ece411.NAND2.generatedInstance
--
-- Created:
--          by - strasbe1.ews (dcl-l520-32.ews.illinois.edu)
--          at - 18:22:23 03/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee; 
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all; 
 
LIBRARY ece411; 
USE ece411.LC3b_types.all; 

ENTITY NAND2 IS
   PORT( 
      MemWrite  : OUT    std_logic;
      MWRITEH_L : IN     std_logic;
      MWRITEL_L : IN     std_logic
   );

END NAND2 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF NAND2 IS 
BEGIN


END generatedInstance;
