-- VHDL Entity ece411.WaySelect.interface
--
-- Created:
--          by - strasbe1.ews (gelib-057-28.ews.illinois.edu)
--          at - 22:05:56 03/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee; 
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all; 
 
LIBRARY ece411; 
USE ece411.LC3b_types.all; 

ENTITY WaySelect IS
   PORT( 
      DirtyState : IN     std_logic;
      LRUNotOut  : IN     std_logic;
      Way1Hit    : IN     std_logic;
      OWordSel   : OUT    std_logic
   );

-- Declarations

END WaySelect ;

--
-- VHDL Architecture ece411.WaySelect.struct
--
-- Created:
--          by - strasbe1.ews (gelib-057-28.ews.illinois.edu)
--          at - 22:05:56 03/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee; 
USE ieee.std_logic_1164.all; 
USE ieee.NUMERIC_STD.all; 
 
LIBRARY ece411; 
USE ece411.LC3b_types.all; 


ARCHITECTURE struct OF WaySelect IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT STDLogicMux
   PORT (
      DirtyState : IN     std_logic ;
      LRUNotOut  : IN     std_logic ;
      Way1Hit    : IN     std_logic ;
      OWordSel   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : STDLogicMux USE ENTITY ece411.STDLogicMux;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : STDLogicMux
      PORT MAP (
         DirtyState => DirtyState,
         LRUNotOut  => LRUNotOut,
         Way1Hit    => Way1Hit,
         OWordSel   => OWordSel
      );

END struct;
